apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170970329
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170970329
    app.kubernetes.io/part-of: test-app-170970329
  name: java-quarkus-170970329
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170970329
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170970329
    spec:
      containers:
      - image: quay.io/hacdev/48r7hhm6-tenant/test-app-170970329/java-quarkus-170970329@sha256:3e2fc834162c1f02809a693c031305b4695824afb0879c931208e6648e0b3109
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
